name: pkgcheck

on:
  push:
    branches: [master]
  pull_request:
  # Manually trigger the Action under Actions/pkgcheck
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run pkgcheck
      uses: pkgcore/pkgcheck-action@v1
