name: pkgcheck

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run pkgcheck
      # upstream needs fix: https://github.com/pkgcore/pkgcheck-action/issues/4
      #uses: pkgcore/pkgcheck-action@v1
      uses: nabbi/pkgcheck-action@v1
