name: repoman

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup master gentoo repository
      run: |
        ./.github/setup-master-gentoo.sh
    - name: Setup and run Repoman
      run: |
        ./.github/setup-and-run-repoman.sh
