name: repoman

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
    repoman:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: lucianposton/repoman-ebuild-qa-action@v1
              continue-on-error: true
              with:
                portage_version: latest
